CREATE TABLE role_user (
  id         INT PRIMARY KEY      AUTO_INCREMENT,
  user_id    INT(11)     NOT NULL,
  role       VARCHAR(32) NOT NULL DEFAULT 'ROLE_USER'
  COMMENT 'ROLE_USER:普通用户 ROLE_ADMIN:管理员',
  created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);